re_pattern = {
    "google_api": "AIza[0-9A-Za-z-_]{35}",
    "google_captcha": "6L[0-9A-Za-z-_]{38}|^6[0-9a-zA-Z_-]{39}$",
    "google_oauth": "ya29\\.[0-9A-Za-z\\-_]+",
    "amazon_aws_access_key_id": "A[SK]IA[0-9A-Z]{16}",
    "amazon_mws_auth_toke": "amzn\\\\.mws\\\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
    "amazon_aws_url": "s3\\.amazonaws.com[/]+|[a-zA-Z0-9_-]*\\.s3\\.amazonaws.com",
    "facebook_access_token": "EAACEdEose0cBA[0-9A-Za-z]+",
    "authorization_basic": "basic [a-zA-Z0-9=:_-]{5,100}",
    "authorization_bearer": "bearer [a-zA-Z0-9_.=:_\\+\\/-]{5,100}",
    "authorization_api": "api[key|_key|\\s+]+[a-zA-Z0-9_-]{5,100}",
    "mailgun_api_key": "key-[0-9a-zA-Z]{32}",
    "twilio_api_key": "SK[0-9a-fA-F]{32}",
    "twilio_account_sid": "AC[a-zA-Z0-9_-]{32}",
    "twilio_app_sid": "AP[a-zA-Z0-9_-]{32}",
    "paypal_braintree_access_token": "access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}",
    "square_oauth_secret": "sq0csp-[ 0-9A-Za-z_-]{43}|sq0[a-z]{3}-[0-9A-Za-z_-]{22,43}",
    "square_access_token": "sqOatp-[0-9A-Za-z_-]{22}|EAAA[a-zA-Z0-9]{60}",
    "stripe_standard_api": "sk_live_[0-9a-zA-Zhappy_urls.txt]{24}",
    "stripe_restricted_api": "rk_live_[0-9a-zA-Z]{24}",
    "github_access_token": "[a-zA-Z0-9_-]*:[a-zA-Z0-9_\\-]+@github\\.com*",
    "rsa_private_key": "-----BEGIN RSA PRIVATE KEY-----",
    "ssh_dsa_private_key": "-----BEGIN DSA PRIVATE KEY-----",
    "ssh_dc_private_key": "-----BEGIN EC PRIVATE KEY-----",
    "pgp_private_block": "-----BEGIN PGP PRIVATE KEY BLOCK-----",
    "json_web_token": "ey[A-Za-z0-9_=-]+.[A-Za-z0-9_=-]+\\.?[A-Za-z0-9_.+/=-]*$",
    "Passwords": "/password\\s*[=:]\\s*['|\"]?[A-Za-z0-9!@#$%^&*()_+{}\\[\\]:;<>,.?\\/|\\-~\\]{8,}['|\"]?/",
    "Slack Webhooks": "https:\\/\\/hooks\\.slack\\.com\\/services\\/[A-Z0-9]{10}\\/[A-Z0-9]{10}\\/[A-Za-z0-9]{24}",
    "Google API-key": "AIza[0-9A-Za-z_-]{35}",
    "PayPal Client IDs": "AY-[A-Za-z0-9_-]{22}",
    "IsAdmin": "isadmin",
    "SSH private keys": "/BEGIN\\sRSA\\sPRIVATE\\shappy_urls.txtKEY|BEGIN\\sPRIVATE\\sKEY/",
    "Access tokens": "/Bearer\\s[a-zA-Z0-9-._~+/]+/",
    "Authorization": "/Authorization:\\s[a-zA-Z0-9-._~+/]+/",
    "Private Keys": "/-----BEGIN (RSA|PRIVATE|OPENSSH) KEY-----[^-]*-----END (RSA|PRIVATE|OPENSSH) KEY-----/s",
    "Twilio API Keys": "/SK[0-9a-fA-F]{32}|AC[a-z0-9]{32}/",
    "Facebook Access Tokens": "/(?:EAACEdEose0c|EAAG|EAAK|EAAF)[A-Za-z0-9]+/",
    "Twilio Account SID": "AC[a-z0-9]{32}",
    "SendGrid API Key": "SG\\.[a-zA-Z0-9_-]{22}\\.[a-zA-Z0-9_-]{43}",
    "Mailgun API Key": "key-[0-9a-zA-Z]{32}",
    "Stripe API Key": "sk_live_[0-9a-zA-Z]{24}",
    "Slack Token": "xox[baprs]-([0-9a-zA-Z]{10,48})?",
    "Facebook Access Token": "EAACEdEose0cBA[0-9A-Za-z]+",
    "GitHub Access Token": "[0-9a-f]{40}",
    "Square Access Token": "sq0atp-[0-9A-Za-z_-]{22}",
    "Square OAuth Secret": "sq0csp-[0-9A-Za-zhappy_urls.txt_-]{43}",
    "Twilio API Key": "SK[a-z0-9]{32}",
    "Slack Legacy Token": "xoxp-[0-9A-Z]{10,12}-[0-9A-Za-z]{24}",
    "AWS access key": "access_key_id\\W+[A-Z0-9]{20}",
    "Firebase API key": "firebase\\W+[A-Za-z0-9_-]{39}",
    "Twilio API key": "TWILIO_ACCOUNT_SID\\W+[A-Za-z0-9]{34}",
    "Square API key": "sq0atp-\\w{22}",
    "Google Maps API key": "AIzaSy[A-Za-z0-9_-]{33}",
    "Google OAuth client ID": "client_id\"\\W*:\\W*\"[0-9]+-[A-Za-z0-9_]+\\.apps\\.googleusercontent\\.com\"",
    "Google Cloud Platform API key": "AIzaSy[A-Za-z0-9_-]{33}",
    "Google reCAPTCHA API key": "sitekehappy_urls.txty\"\\W*:\\W*\"[A-Za-z0-9_-]{40}\"",
    "LinkedIn API key": "linkedin\\W+[A-Za-z0-9_-]{12}",
    "MailChimp API key": "[0-9a-f]{32}-us[0-9]{1,2}",
    "Slack API key": "xox[baprs]-([0-9a-zA-Z]{10,48})?",
    "AWS Access Key ID": "AKIA[0-9A-Z]{16}",
    "Google API Key": "AIza[0-9A-Za-z_-]{35}",
    "AWS Access key": "((?:A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16})",
    "Amazon_AWS_Auth_Token": "(amzn\\\\.mws\\\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})",
    "Zapier Webhook Token": "(https://(?:www.)?hooks\\.zapier\\.com/hooks/catch/[A-Za-z0-9]+/[A-Za-z0-9]+/)",
    "Stripe Secret Key": "([prs]k_(?:live|test)_[0-9a-zA-Z]{24})",
    "Slack Bot": "(xoxb-[0-9A-Za-z\\\\-]{51})",
    "Slack user": "(xoxp-[0-9A-Za-z\\\\-]{72})",
    "Slack Webhook": "(https://hooks\\\\.slack\\\\.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24})",
    "Braintree-access-token": "(access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32})",
    "Zoho Webhook": "(https://creator\\.zoho\\.com/api/[A-Za-z0-9/_.-]+\\?authtoken=[A-Za-z0-9]+)",
    "Firebase-server-key": "(AAAA[a-zA-Z0-9_-]{7}:[a-zA-Z0-9_-]{140})",
    "oauth-access-key": "(ya29\\.[0-9A-Za-z_-]+)",
    "google-calendar-link": "(https://www\\.google\\.com/calendar/embed\\?src=[A-Za-z0-9%@&;=_./-]+)",
    "google-api-key": "(AIza[0-9A-Za-z_\\\\-]{35})",
    "general token": "(eyJ[a-zA-Z0-9]{10,}\\.eyJ[a-zA-Z0-9]{10,}\\.[a-zA-Z0-9_-]{10,})",
    "jdbc-connection-string": "(jdbc:[a-z:]+://[A-Za-z0-9\\.\\-_:;=/@?,&]+)",
    "credentials-disclosure": "(zopim[_-]?account[_-]?key(=| =|:| :))",
    "Zhuliang Token": "(zhuliang[_-]?gh[_-]?token(=| =|:| :))",
    "Zensona": "(zensonatypepassword(=| =|:| :))",
    "Picatic-api-key": "(sk_live_[0-9a-z]{32})",
    "artifactory-api-token": "((?:\\s|=|:|\"|^)AKC[a-zA-Z0-9]{10,})",
    "artifactory-api-password": "((?:\\s|=|:|\"|^)AP[\\dABCDEF][a-zA-Z0-9]{8,})",
    "amazon-sns-topic": "(arn:aws:sns:[a-z0-9\\-]+:[0-9]+:[A-Za-z0-9\\-_]+)",
    "microsoft-teams-webhook": "(https://outlook\\.office\\.com/webhook/[A-Za-z0-9@-]+/IncomingWebhook/[A-Za-z0-9-]+/[A-Za-z0-9-]+)",
    "sonarqube-token": "(sonar.{0,50}(?:\"|\\'|`)?[0-9a-f]{40}(?:\"|\\'|`)?)",
    "bitly-secret-key": "(R_[0-9a-f]{32})",
    "sendgrid-api-key": "(SG\\.[a-zA-Z0-9_-]{22}\\.[a-zA-Z0-9_-]{43})",
    "discord-webhook": "(https://discordapp\\.com/api/webhooks/[0-9]+/[A-Za-z0-9-]+)",
    "cloudinary-credentials": "(cloudinary://[0-9]+:[A-Za-z0-9_.-]+@[A-Za-z0-9_.-]+)",
    "SSH_privKey": "([-]+BEGIN [^\\s]+ PRIVATE KEY[-]+[\\s]*[^-]*[-]+END [^\\s]+ PRIVATE KEY[-]+)",
    "Heroku API KEY": "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
    "API_Key": "(?i)apikey\\s?[=|:]\\s?([\"|\\'].*[\"|\\'])(?= ;)"
}